AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Scheduled Lambda with secret, S3 access, and logging

Parameters:
  S3BucketName:
    Type: String
    Description: S3 bucket to store Lambda output

Globals:
  Function:
    Handler: lambda_function.lambda_handler

Resources:
  ServiceNowDataAnalysisSecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: service-now-data-analysis-secret
      Description: Secret for Lambda
      SecretString: !Sub |
        {
          "username": "*******",
          "password": "*******",
          "instance": "*******"
        }

  ServiceNowDataAnalysisLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: service-now-data-analysis-lambda-execution-role
      Description: Role for ServiceNow data analysis Lambda function
      AssumeRolePolicyDocument:
        Version: '2012-10-17' 
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Ref ServiceNowDataAnalysisSecret
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"
              - Effect: Allow
                Action:
                  - s3:PutObject
                Resource: !Sub "arn:aws:s3:::${S3BucketName}/*"

  ServiceNowDataAnalysisLambdaInvokeRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: "service-now-data-analysis-lambda-invoke-role"
      Description: Role for invoking ServiceNow data analysis Lambda function
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: scheduler.amazonaws.com  # For AWS Scheduler
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AllowInvokeLambda
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: lambda:InvokeFunction
                Resource: !GetAtt ServiceNowDataAnalysisDataIngestionLambda.Arn

  ServiceNowDataAnalysisRequestsLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: "service-now-data-analysis-requests-layer"
      Description: Requests package for Lambda
      Content:
        S3Bucket: !Ref S3BucketName
        S3Key: !Join ["/", ["layers", "requests_layer.zip"] ]
      CompatibleRuntimes:
        - python3.11
      CompatibleArchitectures:
        - x86_64

  ServiceNowDataAnalysisDataIngestionLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "service-now-data-ingestion-lambda"
      Handler: index.handler
      Runtime: python3.11
      CodeUri: functions/service-now-data-ingestion-lambda/
      Description: Lambda function for ServiceNow data ingestion
      Role: !GetAtt ServiceNowDataAnalysisLambdaExecutionRole.Arn
      Timeout: 900
      MemorySize: 1024
      Environment:
        Variables:
          SERVICENOW_SECRET_NAME: !Ref ServiceNowDataAnalysisSecret
      Layers:
        - !Ref ServiceNowDataAnalysisRequestsLayer

  ServiceNowDataAnalysisDataIngestionLambdaSchedule:
    Type: AWS::Scheduler::Schedule
    Properties:
      Name: "service-now-data-ingestion-schedule"
      ScheduleExpression: "cron(0/30 * * * ? *)"
      FlexibleTimeWindow:
        Mode: "OFF"
      Target:
        Arn: !GetAtt ServiceNowDataAnalysisDataIngestionLambda.Arn
        RoleArn: !GetAtt ServiceNowDataAnalysisLambdaInvokeRole.Arn

  LambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ServiceNowDataAnalysisDataIngestionLambda}"
      RetentionInDays: 7

Outputs:
  ServiceNowLambda:
    Description: Name of the Lambda function
    Value: !Ref ServiceNowDataAnalysisDataIngestionLambda